name       : volk
version    : 2.4.1
release    : 1
source     :
    - https://github.com/gnuradio/volk/releases/download/v2.4.1/volk-2.4.1.tar.xz : 1fabeea2a6332bb58370b46fc0d7164aa6625c9fb50a5f65fc7cf8832990cbf5
license    : GPL-3.0-or-later
homepage   : https://www.libvolk.org
component  : programming.library
summary    : VOLK is the Vector-Optimized Library of Kernels
description: |
    It is a library that contains kernels of hand-written SIMD code for different mathematical operations.
builddeps  :
    - mako
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install